{"name": "test_fail", "status": "failed", "statusDetails": {"message": "AssertionError: 1 != 2", "trace": "self = <test_demo.TestStringMethods testMethod=test_fail>\n\n    def test_fail(self):\n        \"\"\" This test should fail. \"\"\"\n>       self.assertEqual(1, 2)\nE       AssertionError: 1 != 2\n\ntest_demo.py:16: AssertionError"}, "description": " This test should fail. ", "start": 1697881924058, "stop": 1697881924062, "uuid": "e93df556-2831-41f2-bb9a-997dbf2f0338", "historyId": "571d010ca0fcd3a92849e7e7bdf27b23", "testCaseId": "571d010ca0fcd3a92849e7e7bdf27b23", "fullName": "test_demo.TestStringMethods#test_fail", "labels": [{"name": "suite", "value": "test_demo"}, {"name": "subSuite", "value": "TestStringMethods"}, {"name": "host", "value": "DESKTOP-M8MOJ3U"}, {"name": "thread", "value": "9880-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_demo"}]}